# Generated by Django 4.2.30 on 2026-08-27 16:56

from django.db import migrations, models


def preserve_display_names(apps, schema_editor):
    ProviderProfile = apps.get_model('accounts', 'ProviderProfile')
    ProviderProfile.objects.filter(display_name='').exclude(business_name='').update(
        display_name=models.F('business_name')
    )


def restore_business_names(apps, schema_editor):
    # The field is removed after this migration and cannot be restored safely
    # from display_name alone; the reverse operation is intentionally a no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_providerverificationrequest_documents_and_more'),
    ]

    operations = [
        migrations.RunPython(preserve_display_names, restore_business_names),
        migrations.RemoveField(
            model_name='providerprofile',
            name='business_name',
        ),
    ]
