# Generated by Django 4.2.30 on 2026-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_legacy_profile_duplicates"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="providerdocument",
            constraint=models.UniqueConstraint(
                fields=("provider", "document_type"),
                name="unique_provider_document_type",
            ),
        ),
    ]
