import json, re, subprocess
from pathlib import Path
D=json.load(open('/home/ubuntu/selvvv/db_inspection.json'))
ROOT=Path('/home/ubuntu/selvvv/docs/diagrams_ar'); ROOT.mkdir(parents=True,exist_ok=True)
T={t['name']:t for t in D['tables']}
AR={
'accounts_user':'المستخدمون','accounts_providerprofile':'ملفات مقدمي الخدمات','accounts_providerdocumenttype':'أنواع مستندات مقدم الخدمة','accounts_providerdocument':'مستندات مقدم الخدمة','accounts_providerverificationrequest':'طلبات توثيق مقدم الخدمة','accounts_providerprofile_qualification_choices':'اختيارات المؤهلات','accounts_providerprofile_specializations':'اختيارات التخصصات','accounts_providerverificationrequest_documents':'مستندات طلب التوثيق','accounts_providerverificationrequest_requested_services':'خدمات طلب التوثيق','accounts_user_groups':'مستخدمون ومجموعات','accounts_user_user_permissions':'صلاحيات المستخدمين','auth_group':'المجموعات','auth_group_permissions':'صلاحيات المجموعات','auth_permission':'الصلاحيات','django_content_type':'أنواع المحتوى','django_admin_log':'سجل الإدارة','django_migrations':'سجل الهجرات','django_session':'جلسات الدخول','chat_conversation':'المحادثات','chat_message':'الرسائل','core_auditlog':'السجل التدقيقي','core_city':'المدن','core_district':'المديريات','core_notification':'الإشعارات','core_platformsetting':'إعدادات المنصة','core_termsacceptance':'قبول الشروط','core_termsandconditions':'الشروط والأحكام','marketplace_category':'تصنيفات الخدمات','marketplace_managedservice':'الخدمات المركزية','marketplace_providerservice':'خدمات مقدمي الخدمات','marketplace_qualification':'المؤهلات','marketplace_service':'الخدمات المنشورة','marketplace_specialization':'التخصصات','orders_delivery':'التسليمات','orders_milestone':'مراحل الطلب','orders_order':'الطلبات','orders_ordermessage':'رسائل الطلبات','payments_commissionrecord':'سجلات العمولات','payments_payment':'المدفوعات','payments_providerwallet':'محافظ مقدمي الخدمات','payments_wallet':'أنواع المحافظ','reviews_review':'التقييمات والمراجعات'}
FIELD={'id':'المعرّف','user_id':'المستخدم','provider_id':'مقدم الخدمة','customer_id':'العميل','service_id':'الخدمة','category_id':'التصنيف','city_id':'المدينة','location_city_id':'مدينة الموقع','district_id':'المديرية','location_district_id':'مديرية الموقع','reviewed_by_id':'راجع السجل','verified_by_id':'موثّق بواسطة','document_type_id':'نوع المستند','providerprofile_id':'ملف مقدم الخدمة','qualification_id':'المؤهل','specialization_id':'التخصص','providerverificationrequest_id':'طلب التوثيق','providerdocument_id':'مستند مقدم الخدمة','managedservice_id':'الخدمة المركزية','catalog_service_id':'الخدمة المركزية','provider_service_id':'خدمة مقدم الخدمة','order_id':'الطلب','sender_id':'المرسل','conversation_id':'المحادثة','payment_id':'الدفعة','provider_wallet_id':'محفظة مقدم الخدمة','wallet_id':'المحفظة','terms_id':'الشروط','recipient_id':'المستلم','content_type_id':'نوع المحتوى','group_id':'المجموعة','permission_id':'الصلاحية','parent_id':'التصنيف الأب','name':'الاسم','title':'العنوان','status':'الحالة','role':'الدور','amount':'المبلغ','price':'السعر','created_at':'تاريخ الإنشاء','updated_at':'تاريخ التحديث','is_active':'نشط','is_available':'متاح','is_public':'عام','order_number':'رقم الطلب','transaction_id':'رقم العملية','review_note':'ملاحظة المراجعة','description':'الوصف','message':'الرسالة','comment':'التعليق','file':'الملف','code':'الرمز','email':'البريد الإلكتروني','phone':'الهاتف'}
COLORS={'accounts':'#dbeafe','core':'#dcfce7','marketplace':'#fef3c7','orders':'#ffedd5','payments':'#fce7f3','reviews':'#ede9fe','chat':'#cffafe','auth':'#f1f5f9','django':'#f1f5f9'}
def esc(s): return s.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('"','&quot;')
def node_id(name): return 'n_'+re.sub('[^A-Za-z0-9_]','_',name)
def domain(name): return name.split('_')[0]
def label_fields(t, full=False):
 fks={f['from'] for f in t['foreign_keys']}
 chosen=[]
 for c in t['columns']:
  if full or c['pk'] or c['name'] in fks or c['name'] in ['name','title','status','role','amount','price','created_at','is_active','is_available','order_number']:
   tag=' (PK)' if c['pk'] else (' (FK)' if c['name'] in fks else '')
   chosen.append(f'{FIELD.get(c["name"], "حقل "+c["name"])}{tag} : {c["type"]}')
 return '<BR ALIGN="RIGHT"/>'.join(esc(x) for x in chosen)
def make_node(t, full=False, cls='entity'):
 fill=COLORS.get(domain(t['name']),'#e5e7eb')
 return f'{node_id(t["name"])} [shape=plain, label=<<TABLE BORDER="1" CELLBORDER="0" CELLSPACING="0" CELLPADDING="5" BGCOLOR="{fill}"><TR><TD><B>{esc(AR[t["name"]])}</B></TD></TR><TR><TD ALIGN="RIGHT">{label_fields(t,full)}</TD></TR></TABLE>>];'
def edges():
 out=[]
 for t in D['tables']:
  for f in t['foreign_keys']:
   parent=T[f['table']]; unique=any(ix['unique'] and [x['name'] for x in ix['columns']]==[f['from']] for ix in t['indexes'])
   card='1 : 1' if unique else '1 : متعدد'
   out.append(f'{node_id(t["name"])} -> {node_id(parent["name"])} [label="{f["from"]} | {card}", fontsize=9];')
 return out
def header(title):
 return f'digraph G {{\n graph [fontname="Noto Sans Arabic", labelloc="t", label="{title}", fontsize=24, rankdir=LR, splines=ortho, nodesep=0.35, ranksep=1.0, pad=0.3, bgcolor="white"];\n node [fontname="Noto Sans Arabic"]; edge [fontname="Noto Sans Arabic", color="#64748b", arrowsize=0.7];\n'
def footer():
 return ' legend [shape=note, label="PK = مفتاح أساسي    FK = مفتاح أجنبي    1 : متعدد = واحد إلى متعدد    1 : 1 = واحد إلى واحد", fontname="Noto Sans Arabic", fontsize=12, fillcolor="#f8fafc", style="filled"];\n}\n'
# Full ERD: all real tables, Arabic display names, key fields and all official FK edges.
for fname,title,full in [('01_مخطط_العلاقات_ERD','الشكل (1) — مخطط الكيانات والعلاقات الكامل',False),('06_مخطط_بنية_قاعدة_البيانات','الشكل (6) — مخطط بنية قاعدة البيانات التفصيلي',True)]:
 s=header(title)
 for t in D['tables']: s+=make_node(t,full)+'\n'
 s+='\n'.join(edges())+'\n'+footer(); (ROOT/(fname+'.dot')).write_text(s)
# Class diagram uses readable Arabic class names and domain fields.
classes={'accounts_user':'المستخدم','accounts_providerprofile':'ملف مقدم الخدمة','core_city':'مدينة','core_district':'مديرية','marketplace_category':'تصنيف','marketplace_managedservice':'خدمة مركزية','marketplace_providerservice':'خدمة مقدم','marketplace_service':'خدمة منشورة','marketplace_specialization':'تخصص','marketplace_qualification':'مؤهل','orders_order':'طلب','orders_delivery':'تسليم','orders_milestone':'مرحلة طلب','orders_ordermessage':'رسالة طلب','payments_wallet':'محفظة','payments_providerwallet':'محفظة مقدم','payments_payment':'دفعة','payments_commissionrecord':'عمولة','reviews_review':'مراجعة','chat_conversation':'محادثة','chat_message':'رسالة','accounts_providerdocumenttype':'نوع مستند','accounts_providerdocument':'مستند','accounts_providerverificationrequest':'طلب توثيق','core_notification':'إشعار','core_auditlog':'سجل تدقيقي','core_termsandconditions':'شروط وأحكام','core_termsacceptance':'قبول الشروط','core_platformsetting':'إعداد منصة'}
s=header('الشكل (2) — مخطط الفئات والعلاقات')
for table,ar in classes.items():
 t=T[table]; fill=COLORS.get(domain(table),'#e5e7eb'); s+=f'{node_id(table)} [shape=plain, label=<<TABLE BORDER="1" CELLBORDER="0" CELLSPACING="0" CELLPADDING="5" BGCOLOR="{fill}"><TR><TD><B>{esc(ar)}</B></TD></TR><TR><TD ALIGN="RIGHT">{label_fields(t,False)}</TD></TR></TABLE>>];\n'
for t in D['tables']:
 if t['name'] not in classes: continue
 for f in t['foreign_keys']:
  if f['table'] in classes: s+=f'{node_id(t["name"])} -> {node_id(f["table"])} [label="{FIELD.get(f["from"],f["from"])}", fontsize=9];\n'
s+=footer(); (ROOT/'02_مخطط_الفئات.dot').write_text(s)
# DFDs are manually organized with clear columns and Arabic labels.
ctx='''digraph G { graph [fontname="Noto Sans Arabic", label="الشكل (3) — مخطط السياق / المستوى الصفري", labelloc="t", fontsize=24, rankdir=LR, splines=ortho, nodesep=.8, ranksep=1.1, bgcolor="white"]; node [fontname="Noto Sans Arabic", shape=box, style="rounded,filled", fillcolor="#dbeafe"]; edge [fontname="Noto Sans Arabic", color="#2563eb", arrowsize=.8]; عميل [label="العميل", fillcolor="#fef3c7"]; مقدم [label="مقدم الخدمة", fillcolor="#dcfce7"]; مدير [label="المدير", fillcolor="#fce7f3"]; نظام [label="منصة selvvv\nإدارة سوق الخدمات", shape=ellipse, fillcolor="#dbeafe", penwidth=2]; دفع [label="المحفظة / وسيلة الدفع", fillcolor="#ede9fe"]; عميل -> نظام [label="تسجيل، بحث، طلب، رسائل، تقييم"]; مقدم -> نظام [label="ملف، خدمات، مستندات، تحديثات الطلب"]; مدير -> نظام [label="إدارة، توثيق، مراجعة دفع، تقارير"]; دفع -> نظام [label="مرجع العملية / حالة الدفع"]; نظام -> عميل [label="نتائج البحث، حالة الطلب، إشعارات، نتيجة الدفع"]; نظام -> مقدم [label="طلبات العملاء، قرارات التوثيق، حالة الدفع"]; نظام -> مدير [label="لوحات وتقارير وسجل تدقيقي"]; نظام -> دفع [label="طلب دفع / سند للمراجعة"]; }'''
(ROOT/'03_مخطط_السياق_المستوى_الصفري.dot').write_text(ctx)
dfd1='''digraph G { graph [fontname="Noto Sans Arabic", label="الشكل (4) — مخطط تدفق البيانات المستوى الأول", labelloc="t", fontsize=24, rankdir=LR, splines=ortho, nodesep=.55, ranksep=1.0, bgcolor="white"]; node [fontname="Noto Sans Arabic"]; edge [fontname="Noto Sans Arabic", color="#64748b", arrowsize=.7]; customer [label="العميل", shape=box, style=filled, fillcolor="#fef3c7"]; provider [label="مقدم الخدمة", shape=box, style=filled, fillcolor="#dcfce7"]; admin [label="المدير", shape=box, style=filled, fillcolor="#fce7f3"]; p1 [label="1\nالحساب والمصادقة", shape=circle, style=filled, fillcolor="#dbeafe"]; p2 [label="2\nتصفح وإدارة الخدمات", shape=circle, style=filled, fillcolor="#dbeafe"]; p3 [label="3\nتوثيق مقدم الخدمة", shape=circle, style=filled, fillcolor="#dbeafe"]; p4 [label="4\nإنشاء وإدارة الطلبات", shape=circle, style=filled, fillcolor="#dbeafe"]; p5 [label="5\nالدفع والعمولات", shape=circle, style=filled, fillcolor="#dbeafe"]; p6 [label="6\nالمراجعات والمحادثات", shape=circle, style=filled, fillcolor="#dbeafe"]; p7 [label="7\nلوحة التحكم والتقارير", shape=circle, style=filled, fillcolor="#dbeafe"]; d1 [label="بيانات المستخدمين والجلسات والصلاحيات", shape=cylinder, style=filled, fillcolor="#f1f5f9"]; d2 [label="التصنيفات والخدمات والتخصصات والمؤهلات", shape=cylinder, style=filled, fillcolor="#fef3c7"]; d3 [label="ملفات مقدمي الخدمات والمستندات وطلبات التوثيق", shape=cylinder, style=filled, fillcolor="#dcfce7"]; d4 [label="الطلبات والتسليمات والمراحل ورسائل الطلب", shape=cylinder, style=filled, fillcolor="#ffedd5"]; d5 [label="المدفوعات والمحافظ والعمولات", shape=cylinder, style=filled, fillcolor="#fce7f3"]; d6 [label="التقييمات والمحادثات والرسائل", shape=cylinder, style=filled, fillcolor="#ede9fe"]; n [label="الإشعارات والسجل التدقيقي", shape=cylinder, style=filled, fillcolor="#cffafe"]; g [label="المحفظة / وسيلة الدفع", shape=box, style=filled, fillcolor="#ede9fe"]; customer -> p1 [label="بيانات الدخول"]; provider -> p1 [label="بيانات الدخول"]; admin -> p1 [label="بيانات الدخول"]; customer -> p2 [label="استعلامات الخدمات"]; provider -> p2 [label="إدارة الخدمة"]; admin -> p2 [label="إدارة الكتالوج"]; provider -> p3 [label="ملف ومستندات"]; admin -> p3 [label="قرار التوثيق"]; customer -> p4 [label="طلب خدمة"]; provider -> p4 [label="قبول وتحديث وتسليم"]; customer -> p5 [label="بيانات الدفع"]; admin -> p5 [label="مراجعة السند"]; provider -> p5 [label="حساب المحفظة"]; customer -> p6 [label="تقييم ورسالة"]; provider -> p6 [label="رسالة ورد"]; admin -> p7 [label="تقارير وإدارة"]; p1 -> d1; p2 -> d2; p2 -> d3; p3 -> d3; p4 -> d4; p5 -> d5; p5 -> g; p6 -> d6; p1 -> n; p4 -> n; p6 -> n; p7 -> d1; p7 -> d2; p7 -> d3; p7 -> d5; }'''
(ROOT/'04_مخطط_تدفق_البيانات_المستوى_الأول.dot').write_text(dfd1)
dfd2='''digraph G { graph [fontname="Noto Sans Arabic", label="الشكل (5) — المستوى الثاني: توثيق مقدم الخدمة", labelloc="t", fontsize=24, rankdir=LR, splines=ortho, nodesep=.7, ranksep=1.0, bgcolor="white"]; node [fontname="Noto Sans Arabic"]; edge [fontname="Noto Sans Arabic", color="#64748b", arrowsize=.8]; p [label="مقدم الخدمة", shape=box, style=filled, fillcolor="#dcfce7"]; a [label="المدير", shape=box, style=filled, fillcolor="#fce7f3"]; p1 [label="2.1\nتحديث الملف واختيار الخدمات", shape=circle, style=filled, fillcolor="#dbeafe"]; p2 [label="2.2\nرفع المستندات", shape=circle, style=filled, fillcolor="#dbeafe"]; p3 [label="2.3\nإرسال طلب التوثيق\nوحفظ لقطة البيانات", shape=circle, style=filled, fillcolor="#dbeafe"]; p4 [label="2.4\nمراجعة الطلب والمستندات", shape=circle, style=filled, fillcolor="#dbeafe"]; dec [label="القرار", shape=diamond, style=filled, fillcolor="#fef3c7"]; ok [label="2.5\nاعتماد وتفعيل مقدم الخدمة", shape=circle, style=filled, fillcolor="#dcfce7"]; no [label="2.6\nرفض أو طلب مستندات إضافية", shape=circle, style=filled, fillcolor="#fee2e2"]; d1 [label="ملف مقدم الخدمة\nوالخدمات المختارة", shape=cylinder, style=filled, fillcolor="#dcfce7"]; d2 [label="المستندات", shape=cylinder, style=filled, fillcolor="#fef3c7"]; d3 [label="طلب التوثيق\nولقطة البيانات", shape=cylinder, style=filled, fillcolor="#dbeafe"]; n [label="إشعار + سجل تدقيقي", shape=cylinder, style=filled, fillcolor="#cffafe"]; p -> p1 [label="بيانات الملف"]; p -> p2 [label="ملفات الإثبات"]; p1 -> d1; p2 -> d2; p1 -> p3; p2 -> p3; p3 -> d3; a -> p4 [label="قرار المراجعة"]; d2 -> p4; d3 -> p4; p4 -> dec; dec -> ok [label="مقبول"]; dec -> no [label="مرفوض / يحتاج مستندات"]; ok -> d1; no -> d3; ok -> n; no -> n; n -> p [label="نتيجة التوثيق"]; }'''
(ROOT/'05_مخطط_المستوى_الثاني_للتوثيق.dot').write_text(dfd2)
for dot in ROOT.glob('*.dot'):
 out=dot.with_suffix('.png'); subprocess.run(['dot','-Tpng','-Gdpi=180',str(dot),'-o',str(out)],check=True)
print('generated',len(list(ROOT.glob('*.png'))),'Arabic PNG diagrams')
