# Generated by Django 4.2.30 on 2026-08-27 16:56

from django.db import migrations, models
import django.db.models.deletion


def backfill_provider_service(apps, schema_editor):
    Service = apps.get_model('marketplace', 'Service')
    ProviderService = apps.get_model('marketplace', 'ProviderService')
    for service in Service.objects.filter(provider_service__isnull=True).iterator():
        candidates = ProviderService.objects.filter(
            provider__user_id=service.provider_id,
            catalog_service__category_id=service.category_id,
            catalog_service__is_active=True,
            is_active=True,
            approval_status__in=['approved', 'active'],
        )
        if candidates.count() == 1:
            service.provider_service_id = candidates.values_list('id', flat=True).first()
            service.save(update_fields=['provider_service'])


def reverse_backfill_provider_service(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_providerservice_provider_service_exactly_one_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='provider_service',
            field=models.ForeignKey(blank=True, help_text='الخدمة المركزية المعتمدة التي ينتمي إليها هذا العرض التجاري', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_services', to='marketplace.providerservice', verbose_name='اعتماد مقدم الخدمة'),
        ),
        migrations.RunPython(backfill_provider_service, reverse_backfill_provider_service),
    ]
